### PR TITLE
imx6ull: boot from qspi nor flash

### PR DESCRIPTION
**Pull request by badochov**
JIRA: RTOS-398

## Description
Adjust to booting from nor flash

## Motivation and Context
imx6ull lacks support for starting from flash. Adding this support moves plo ivt to 0x1000.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: imx6ull.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work:
https://github.com/phoenix-rtos/plo/pull/236
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by nalajcie** [comment]
I think sdp scripts for booting from NAND should not be removed in this PR (they are perfectly usable in DTR project)

**Comment by badochov** [comment]
> I think sdp scripts for booting from NAND should not be removed in this PR (they are perfectly usable in DTR project)

I thought they are redundant as DTR already has them copied in separate folder, but I'll restore them as you like it

**Comment by nalajcie** [comment]
> > I think sdp scripts for booting from NAND should not be removed in this PR (they are perfectly usable in DTR project)
> 
> I thought they are redundant as DTR already has them copied in separate folder, but I'll restore them as you like it

 - there is no equivalent of `imx6ull-flash.sdp` (flashing all partitions) and `imx6ull-ram.sdp`
 - still, DTR is a private project, I think the scripts should remain in Open Source as a reference regardless of it's state

**Comment by agkaminski** [comment]
@badochov Yeah, lets keep 'em

**Review by agkaminski — APPROVED** [review]

**Pull request merged**
